version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: agallet
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
      PGPASSOWRD: POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres:/postgres
      - ./customer:/customer
      - ./item:/item
      - ./pie.py:/pie.py
    networks: 
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3000:80"
    networks:
      - pg-network
    depends_on:
      - postgres

networks:
  pg-network:

volumes:
  pgdata:
