version: '3.8'

services:
  postgres:
    build: /postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: agallet
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
