version: '3.8'

services:
  postgres:
    build: ./postgres/
    container_name: postgres-container
    environment:
      POSTGRES_USER: agallet
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - pg-network
    depends_on:
      - postgres

networks:
  pg-network:

volumes:
  postgres-data:
